Repository bean-space/bean-space, pull requests merged in 2024-08, with the labels that each got.

#88 :white_check_mark: 쿠폰 발급, 예약 동시성 제어 테스트 코드 작성
  src/main/kotlin/com/beanspace/beanspace/api/coupon/CouponController.kt
  src/main/kotlin/com/beanspace/beanspace/api/coupon/CouponService.kt
  src/test/kotlin/com/beanspace/beanspace/api/coupon/CouponConcurrencyTest.kt
  src/test/kotlin/com/beanspace/beanspace/api/reservation/ReservationConcurrencyTest.kt
Labels: test

#94 ✨ 쿠폰 발급 및 예약에 대한 동시성 제어 구현
  build.gradle.kts
  src/main/kotlin/com/beanspace/beanspace/api/coupon/CouponService.kt
  src/main/kotlin/com/beanspace/beanspace/api/reservation/ReservationService.kt
  src/main/kotlin/com/beanspace/beanspace/infra/redis/RedisConfig.kt
  src/main/resources/application.yml
  src/test/kotlin/com/beanspace/beanspace/api/coupon/CouponConcurrencyTest.kt
  src/test/kotlin/com/beanspace/beanspace/api/reservation/ReservationServiceTest.kt
Labels: feature

#97 ✨예약목록 확인 수정
  src/main/kotlin/com/beanspace/beanspace/api/member/MemberController.kt
  src/main/kotlin/com/beanspace/beanspace/api/member/MemberService.kt
  src/main/kotlin/com/beanspace/beanspace/api/member/dto/MemberReservationResponse.kt
  src/main/kotlin/com/beanspace/beanspace/domain/reservation/repository/ReservationRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/ReviewRepository.kt
Labels: feature

#98 ✨ Admin 공간 목록 Response 수정
  src/main/kotlin/com/beanspace/beanspace/api/admin/AdminService.kt
  src/main/kotlin/com/beanspace/beanspace/api/admin/dto/RequestAddSpaceResponse.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepositoryImpl.kt
  src/test/kotlin/com/beanspace/beanspace/api/coupon/CouponConcurrencyTest.kt
  src/test/kotlin/com/beanspace/beanspace/api/reservation/ReservationConcurrencyTest.kt
Labels: feature

#100 👷 CI/CD 구축
  .dockerignore
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .gitignore
  Dockerfile
  build.gradle.kts
  src/main/kotlin/com/beanspace/beanspace/api/HealthCheckController.kt
  src/main/kotlin/com/beanspace/beanspace/infra/redis/RedisConfig.kt
  src/main/kotlin/com/beanspace/beanspace/infra/security/config/SecurityConfig.kt
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/kotlin/com/beanspace/beanspace/api/coupon/CouponConcurrencyTest.kt
  src/test/kotlin/com/beanspace/beanspace/api/reservation/ReservationConcurrencyTest.kt
  src/test/kotlin/com/beanspace/beanspace/domain/review/repository/ReviewRepositoryTest.kt
  src/test/resources/application.yml
Labels: feature

#101 ✨ [Host] 예약 현황 조회
  src/main/kotlin/com/beanspace/beanspace/api/admin/AdminService.kt
  src/main/kotlin/com/beanspace/beanspace/api/host/HostController.kt
  src/main/kotlin/com/beanspace/beanspace/api/host/HostService.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/ReviewResponse.kt
  src/main/kotlin/com/beanspace/beanspace/domain/coupon/repository/CouponRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/reservation/repository/ReservationRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceRepository.kt
Labels: feature

#108 :bug: 쿠폰 리스트 조회되지 않는 문제 수정
  src/main/kotlin/com/beanspace/beanspace/domain/coupon/repository/CouponRepositoryImpl.kt
Labels: bug

#107 :sparkles: 쿠폰 발행 중, 발급 완료된 경우 수정 ,삭제 불가 처리
  src/main/kotlin/com/beanspace/beanspace/api/admin/AdminService.kt
Labels: feature

#109 :sparkles: Admin 계정 쿠폰 발급, 예약 기능 제한
  src/main/kotlin/com/beanspace/beanspace/api/coupon/CouponController.kt
  src/main/kotlin/com/beanspace/beanspace/api/reservation/ReservationController.kt
Labels: feature

#110 ✨ 소셜 회원가입 회원 추가 정보 받도록 처리
  src/main/kotlin/com/beanspace/beanspace/api/member/MemberController.kt
  src/main/kotlin/com/beanspace/beanspace/api/member/MemberService.kt
  src/main/kotlin/com/beanspace/beanspace/api/member/dto/MemberProfileResponse.kt
  src/main/kotlin/com/beanspace/beanspace/api/member/dto/UpdateSocialUserInfoRequest.kt
  src/main/kotlin/com/beanspace/beanspace/api/reservation/ReservationService.kt
  src/main/kotlin/com/beanspace/beanspace/domain/member/model/Member.kt
  src/test/kotlin/com/beanspace/beanspace/api/reservation/ReservationServiceTest.kt
Labels: feature

#111 🐛 운영서버 쿠폰 발급 에러 해결
  src/main/kotlin/com/beanspace/beanspace/BeanSpaceApplication.kt
  src/main/kotlin/com/beanspace/beanspace/api/coupon/CouponService.kt
  src/main/kotlin/com/beanspace/beanspace/api/reservation/ReservationService.kt
  src/main/kotlin/com/beanspace/beanspace/infra/security/config/SecurityConfig.kt
  src/main/resources/application-prod.yml
Labels: bug

#112 :sparkles: 공간 목록, 개별 조회시 상세주소가 노출되지 않게 수정
  src/main/kotlin/com/beanspace/beanspace/api/space/SpaceController.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/SpaceService.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/SpaceDetailResponse.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/SpaceResponseWithoutAddress.kt
Labels: feature

#115 ✅ 엔티티 도메인 로직 테스트 코드 추가
  src/main/kotlin/com/beanspace/beanspace/api/reservation/ReservationService.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/SpaceService.kt
  src/main/kotlin/com/beanspace/beanspace/domain/coupon/model/Coupon.kt
  src/main/kotlin/com/beanspace/beanspace/domain/reservation/model/Reservation.kt
  src/test/kotlin/com/beanspace/beanspace/api/reservation/ReservationServiceTest.kt
  src/test/kotlin/com/beanspace/beanspace/api/space/SpaceServiceTest.kt
  src/test/kotlin/com/beanspace/beanspace/domain/coupon/model/CouponTest.kt
  src/test/kotlin/com/beanspace/beanspace/domain/reservation/model/ReservationTest.kt
  src/test/kotlin/com/beanspace/beanspace/domain/space/model/SpaceTest.kt
Labels: test

#117 :sparkles: 전체적인 삭제 정책 검사 및 수정
  src/main/kotlin/com/beanspace/beanspace/api/host/HostService.kt
  src/main/kotlin/com/beanspace/beanspace/api/member/MemberService.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/SpaceService.kt
  src/main/kotlin/com/beanspace/beanspace/domain/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/beanspace/beanspace/domain/reservation/repository/ReservationRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/model/Review.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/ReviewRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/WishListRepository.kt
Labels: feature

#122 :sparkles: 검색 기능 구현
  src/main/kotlin/com/beanspace/beanspace/api/admin/dto/RequestAddSpaceResponse.kt
  src/main/kotlin/com/beanspace/beanspace/api/host/HostService.kt
  src/main/kotlin/com/beanspace/beanspace/api/host/dto/AddSpaceRequest.kt
  src/main/kotlin/com/beanspace/beanspace/api/host/dto/UpdateSpaceRequest.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/SpaceController.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/SpaceService.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/SpaceDetailResponse.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/SpaceResponse.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/SpaceResponseWithoutAddress.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/WishListedSpaceResponse.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/model/Address.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/model/SearchKeyword.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/model/SpaceOffer.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/OfferRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SearchKeywordRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceOfferRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepositoryImpl.kt
  src/test/kotlin/com/beanspace/beanspace/api/space/SpaceServiceTest.kt
  src/test/kotlin/com/beanspace/beanspace/domain/review/repository/ReviewRepositoryTest.kt
  src/test/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepositoryTest.kt
Labels: feature

#126 🔧 모니터링을 위한 설정 추가
  .github/workflows/deploy.yml
  build.gradle.kts
  src/main/kotlin/com/beanspace/beanspace/infra/security/config/SecurityConfig.kt
  src/main/resources/application-prod.yml
Labels: infra

#127 🐛 프로필 수정, 소셜 회원 정보 입력 메소드 수정
  src/main/kotlin/com/beanspace/beanspace/api/member/MemberController.kt
Labels: bug

#131 :sparkles: 프로필 수정, 소셜 로그인 유저 정보 추가시 받는 정보 수정
  src/main/kotlin/com/beanspace/beanspace/api/member/MemberService.kt
  src/main/kotlin/com/beanspace/beanspace/api/member/dto/UpdateProfileRequest.kt
  src/main/kotlin/com/beanspace/beanspace/api/member/dto/UpdateSocialUserInfoRequest.kt
  src/main/kotlin/com/beanspace/beanspace/domain/member/model/Member.kt
Labels: feature

#135 🐛 삭제된 공간이 조회되는 버그 수정
  src/main/kotlin/com/beanspace/beanspace/api/space/SpaceService.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/model/Space.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepositoryImpl.kt
  src/test/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepositoryTest.kt
Labels: bug

#136 :sparkles: 편의시설 목록 조회 추가
  src/main/kotlin/com/beanspace/beanspace/api/space/SpaceController.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/SpaceService.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/OfferResponse.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/model/Space.kt
  src/main/kotlin/com/beanspace/beanspace/infra/security/config/SecurityConfig.kt
  src/test/kotlin/com/beanspace/beanspace/api/space/SpaceServiceTest.kt
Labels: feature

#138 ✨ Host로 전환시 전화번호 여부 확인하도록 수정
  src/main/kotlin/com/beanspace/beanspace/api/member/MemberService.kt
  src/main/kotlin/com/beanspace/beanspace/domain/member/model/Member.kt
  src/test/kotlin/com/beanspace/beanspace/api/space/SpaceServiceTest.kt
Labels: feature

#142 ✨ 검색 정렬 기능 구현 및 공간 목록 response 평균별점 추가
  src/main/kotlin/com/beanspace/beanspace/api/host/HostService.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/SpaceService.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/SpaceDetailResponse.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/SpaceResponse.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/SpaceResponseWithoutAddress.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceOfferRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepositoryImpl.kt
  src/test/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepositoryTest.kt
Labels: feature

#143 🔊 api request/response 로깅 추가 및 모니터링 시스템 구축
  .github/workflows/deploy.yml
  build.gradle.kts
  src/main/kotlin/com/beanspace/beanspace/api/coupon/CouponService.kt
  src/main/kotlin/com/beanspace/beanspace/api/reservation/ReservationService.kt
  src/main/kotlin/com/beanspace/beanspace/infra/log/LogFilter.kt
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/log4j2/log4j2-prod.yml
  src/main/resources/log4j2/log4j2.yml
  src/test/resources/application.yml
  src/test/resources/log4j2.yml
Labels: infra

#144 ✨ 인기 검색어 및 인기 숙소 구현
  src/main/kotlin/com/beanspace/beanspace/api/member/MemberController.kt
  src/main/kotlin/com/beanspace/beanspace/api/member/MemberService.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/SpaceController.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/SpaceService.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/CompactSpaceResponse.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/PopularKeywordsResponse.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SearchKeywordQueryDslRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SearchKeywordQueryDslRepositoryImpl.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SearchKeywordRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepositoryImpl.kt
Labels: feature

#146 🐛 SpaceQueryDslRepository 쿼리 오류 수정
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepositoryImpl.kt
Labels: bug

#150 :bug: Review 이미지 Validation 및 리뷰 작성 로직 수정
  src/main/kotlin/com/beanspace/beanspace/api/member/MemberService.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/SpaceService.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/AddReviewRequest.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/UpdateReviewRequest.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/ReviewRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepositoryImpl.kt
  src/test/kotlin/com/beanspace/beanspace/api/space/SpaceServiceTest.kt
Labels: bug

#153 :bug: 조회되어야할 쿠폰이 조회되지 않는 버그 수정
  src/main/kotlin/com/beanspace/beanspace/domain/coupon/repository/CouponRepositoryImpl.kt
Labels: bug

#155 ✨ 인기 공간 불러오기에 캐시 적용
  src/main/kotlin/com/beanspace/beanspace/BeanSpaceApplication.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/SpaceService.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/CompactSpaceResponse.kt
  src/main/kotlin/com/beanspace/beanspace/infra/redis/RedisConfig.kt
Labels: feature

#156 :sparkles: 오래된 검색어 정리 (스케줄러 설정)
  src/main/kotlin/com/beanspace/beanspace/api/admin/AdminController.kt
  src/main/kotlin/com/beanspace/beanspace/api/admin/AdminService.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SearchKeywordQueryDslRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SearchKeywordQueryDslRepositoryImpl.kt
  src/test/kotlin/com/beanspace/beanspace/api/admin/AdminServiceTest.kt
Labels: feature

#158 🐛 사진 업로드 오류 및 검색 결과 오류 수정
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepositoryImpl.kt
  src/main/kotlin/com/beanspace/beanspace/infra/security/config/SecurityConfig.kt
  src/test/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepositoryTest.kt
Labels: bug

#162 🐛 유효성 검사 추가 및 오버플로우 발생 버그 수정 bug
  src/main/kotlin/com/beanspace/beanspace/api/host/dto/AddSpaceRequest.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/AddReviewRequest.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/model/Space.kt
Labels: bug
