Repository bean-space/bean-space, pull requests merged in 2024-07, with the labels that each got.

#14 ✨ Space 도메인 기본 구조 작성
  src/main/kotlin/com/beanspace/beanspace/domain/space/controller/SpaceController.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/dto/SpaceResponse.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/model/Address.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/model/Space.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/model/SpaceStatus.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepositoryImpl.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/service/SpaceService.kt
  src/main/kotlin/com/beanspace/beanspace/infra/querydsl/QueryDslConfig.kt
Labels: feature

#17 :sparkles: GlobalExceptionHandler와 예외 DTO 추가
  src/main/kotlin/com/beanspace/beanspace/domain/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/beanspace/beanspace/domain/exception/InvalidImageException.kt
  src/main/kotlin/com/beanspace/beanspace/domain/exception/dto/ErrorResponse.kt
Labels: feature

#33 :sparkles: 회원 목록 조회, 공간 관리 기능 구현
  src/main/kotlin/com/beanspace/beanspace/api/admin/AdminController.kt
  src/main/kotlin/com/beanspace/beanspace/api/admin/AdminService.kt
  src/main/kotlin/com/beanspace/beanspace/api/admin/dto/RequestAddSpaceResponse.kt
  src/main/kotlin/com/beanspace/beanspace/api/admin/dto/UpdateSpaceStatus.kt
  src/main/kotlin/com/beanspace/beanspace/api/member/dto/MemberListResponse.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/model/Space.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepositoryImpl.kt
Labels: feature

#35 ✨ S3 이미지 업로드 구현
  build.gradle.kts
  src/main/kotlin/com/beanspace/beanspace/api/image/ImageController.kt
  src/main/kotlin/com/beanspace/beanspace/api/image/ImageService.kt
  src/main/kotlin/com/beanspace/beanspace/api/image/PhotoUpdateRequest.kt
  src/main/kotlin/com/beanspace/beanspace/api/image/PostPhotoRequest.kt
  src/main/kotlin/com/beanspace/beanspace/api/image/PostPhotoResponse.kt
  src/main/kotlin/com/beanspace/beanspace/api/image/PreSignedUrlRequest.kt
  src/main/kotlin/com/beanspace/beanspace/api/image/PreSignedUrlResponse.kt
  src/main/kotlin/com/beanspace/beanspace/domain/image/model/Image.kt
  src/main/kotlin/com/beanspace/beanspace/domain/image/model/ImageType.kt
  src/main/kotlin/com/beanspace/beanspace/domain/image/model/PhotoPost.kt
  src/main/kotlin/com/beanspace/beanspace/domain/image/repository/ImageRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/image/repository/PhotoPostRepository.kt
  src/main/kotlin/com/beanspace/beanspace/infra/s3/S3Config.kt
  src/main/kotlin/com/beanspace/beanspace/infra/s3/S3Service.kt
  src/main/kotlin/com/beanspace/beanspace/infra/s3/imagevalidator/ImageValidator.kt
  src/main/kotlin/com/beanspace/beanspace/infra/s3/imagevalidator/ValidationResult.kt
Labels: feature

#34 :sparkles: 회원가입 기능 구현
  build.gradle.kts
  src/main/kotlin/com/beanspace/beanspace/api/auth/AuthController.kt
  src/main/kotlin/com/beanspace/beanspace/api/auth/AuthService.kt
  src/main/kotlin/com/beanspace/beanspace/api/auth/dto/SignUpRequest.kt
  src/main/kotlin/com/beanspace/beanspace/api/auth/dto/SignUpResponse.kt
  src/main/kotlin/com/beanspace/beanspace/domain/exception/AccessDeniedException.kt
  src/main/kotlin/com/beanspace/beanspace/domain/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/beanspace/beanspace/domain/member/repository/MemberRepository.kt
  src/main/kotlin/com/beanspace/beanspace/infra/security/CustomAccessDeniedHandler.kt
  src/main/kotlin/com/beanspace/beanspace/infra/security/CustomAuthenticationEntrypoint.kt
  src/main/kotlin/com/beanspace/beanspace/infra/security/config/PasswordEncoderConfig.kt
  src/main/kotlin/com/beanspace/beanspace/infra/security/config/SecurityConfig.kt
  src/main/kotlin/com/beanspace/beanspace/infra/security/dto/UserPrincipal.kt
  src/main/kotlin/com/beanspace/beanspace/infra/security/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/com/beanspace/beanspace/infra/security/jwt/JwtAuthenticationToken.kt
  src/main/kotlin/com/beanspace/beanspace/infra/security/jwt/JwtPlugin.kt
  src/main/kotlin/com/beanspace/beanspace/infra/swagger/SwaggerConfig.kt
  src/main/resources/application.yml
Labels: feature

#37 :truck: Image DTO 패키지 이동
  src/main/kotlin/com/beanspace/beanspace/api/image/ImageController.kt
  src/main/kotlin/com/beanspace/beanspace/api/image/ImageService.kt
  src/main/kotlin/com/beanspace/beanspace/api/image/dto/PhotoUpdateRequest.kt
  src/main/kotlin/com/beanspace/beanspace/api/image/dto/PostPhotoRequest.kt
  src/main/kotlin/com/beanspace/beanspace/api/image/dto/PostPhotoResponse.kt
  src/main/kotlin/com/beanspace/beanspace/api/image/dto/PreSignedUrlRequest.kt
  src/main/kotlin/com/beanspace/beanspace/api/image/dto/PreSignedUrlResponse.kt
Labels: feature

#38 :sparkles: 로그인 기능 구현
  src/main/kotlin/com/beanspace/beanspace/api/auth/AuthController.kt
  src/main/kotlin/com/beanspace/beanspace/api/auth/AuthService.kt
  src/main/kotlin/com/beanspace/beanspace/api/auth/dto/LoginRequest.kt
  src/main/kotlin/com/beanspace/beanspace/api/auth/dto/LoginResponse.kt
  src/main/kotlin/com/beanspace/beanspace/api/auth/dto/SignUpRequest.kt
  src/main/kotlin/com/beanspace/beanspace/api/auth/dto/SignUpResponse.kt
  src/main/kotlin/com/beanspace/beanspace/domain/exception/AccessDeniedException.kt
  src/main/kotlin/com/beanspace/beanspace/domain/exception/AuthenticationException.kt
  src/main/kotlin/com/beanspace/beanspace/domain/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/beanspace/beanspace/domain/member/model/Member.kt
  src/main/kotlin/com/beanspace/beanspace/domain/member/repository/MemberRepository.kt
Labels: feature

#39 :sparkles: 쿠폰 CRUD 기능 구현
  src/main/kotlin/com/beanspace/beanspace/api/admin/AdminController.kt
  src/main/kotlin/com/beanspace/beanspace/api/admin/AdminService.kt
  src/main/kotlin/com/beanspace/beanspace/api/coupon/dto/CouponRequest.kt
  src/main/kotlin/com/beanspace/beanspace/domain/coupon/model/Coupon.kt
Labels: feature

#44 :sparkles: 쿠폰 조회, 발급 기능 구현
  src/main/kotlin/com/beanspace/beanspace/api/coupon/CouponController.kt
  src/main/kotlin/com/beanspace/beanspace/api/coupon/CouponService.kt
  src/main/kotlin/com/beanspace/beanspace/api/coupon/dto/CouponResponse.kt
  src/main/kotlin/com/beanspace/beanspace/domain/coupon/model/Coupon.kt
  src/main/kotlin/com/beanspace/beanspace/domain/coupon/repository/CouponRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/coupon/repository/CouponRepositoryImpl.kt
  src/main/kotlin/com/beanspace/beanspace/domain/coupon/repository/CustomCouponRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/coupon/repository/UserCouponRepository.kt
  src/main/kotlin/com/beanspace/beanspace/infra/security/config/SecurityConfig.kt
Labels: feature

#43 ✨ 공간 CRUD 구현
  http/auth.http
  http/host.http
  http/space.http
  src/main/kotlin/com/beanspace/beanspace/api/host/HostController.kt
  src/main/kotlin/com/beanspace/beanspace/api/host/HostService.kt
  src/main/kotlin/com/beanspace/beanspace/api/host/dto/AddSpaceRequest.kt
  src/main/kotlin/com/beanspace/beanspace/api/host/dto/UpdateSpaceRequest.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/SpaceController.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/SpaceService.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/SpaceResponse.kt
  src/main/kotlin/com/beanspace/beanspace/domain/exception/AccessDeniedException.kt
  src/main/kotlin/com/beanspace/beanspace/domain/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/beanspace/beanspace/domain/exception/NoPermissionException.kt
  src/main/kotlin/com/beanspace/beanspace/domain/image/repository/ImageRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/model/Space.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepositoryImpl.kt
  src/main/kotlin/com/beanspace/beanspace/infra/security/config/SecurityConfig.kt
Labels: feature

#45 :sparkles: 프로필 조회, 수정 기능 구현
  src/main/kotlin/com/beanspace/beanspace/api/member/MemberController.kt
  src/main/kotlin/com/beanspace/beanspace/api/member/MemberService.kt
  src/main/kotlin/com/beanspace/beanspace/api/member/dto/MemberProfileResponse.kt
  src/main/kotlin/com/beanspace/beanspace/api/member/dto/UpdateProfileRequest.kt
  src/main/kotlin/com/beanspace/beanspace/domain/member/model/Member.kt
Labels: feature

#46 ✨ 공간 예약/취소 기능 구현
  src/main/kotlin/com/beanspace/beanspace/api/reservation/ReservationController.kt
  src/main/kotlin/com/beanspace/beanspace/api/reservation/ReservationService.kt
  src/main/kotlin/com/beanspace/beanspace/api/reservation/dto/ReservationRequest.kt
  src/main/kotlin/com/beanspace/beanspace/api/reservation/dto/ReservationResponse.kt
  src/main/kotlin/com/beanspace/beanspace/domain/coupon/model/UserCoupon.kt
  src/main/kotlin/com/beanspace/beanspace/domain/reservation/model/Reservation.kt
  src/main/kotlin/com/beanspace/beanspace/domain/reservation/model/ReservationStatus.kt
  src/main/kotlin/com/beanspace/beanspace/domain/reservation/repository/ReservationRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceRepository.kt
Labels: feature

#48 ✨ 찜하기/찜취소 기능 구현
  src/main/kotlin/com/beanspace/beanspace/api/space/SpaceController.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/SpaceService.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/WishListRepository.kt
Labels: feature

#50 :sparkles: 멤버가 보유한 쿠폰 목록 조회 구현
  src/main/kotlin/com/beanspace/beanspace/api/coupon/dto/UserCouponResponse.kt
  src/main/kotlin/com/beanspace/beanspace/api/member/MemberController.kt
  src/main/kotlin/com/beanspace/beanspace/api/member/MemberService.kt
  src/main/kotlin/com/beanspace/beanspace/domain/coupon/repository/CustomUserCouponRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/coupon/repository/UserCouponRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/coupon/repository/UserCouponRepositoryImpl.kt
Labels: feature

#49 ✨ 찜한 공간 목록 조회 구현
  src/main/kotlin/com/beanspace/beanspace/api/member/MemberController.kt
  src/main/kotlin/com/beanspace/beanspace/api/member/MemberService.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/WishListedSpaceResponse.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepositoryImpl.kt
Labels: feature

#51 :sparkles: 호스트 신청 기능 구현
  src/main/kotlin/com/beanspace/beanspace/api/member/MemberController.kt
  src/main/kotlin/com/beanspace/beanspace/api/member/MemberService.kt
  src/main/kotlin/com/beanspace/beanspace/domain/member/model/Member.kt
Labels: feature

#53 :sparkles: 프로필 이미지 업로드, 수정, 삭제 구현
  src/main/kotlin/com/beanspace/beanspace/api/auth/dto/SignUpRequest.kt
  src/main/kotlin/com/beanspace/beanspace/api/member/MemberService.kt
  src/main/kotlin/com/beanspace/beanspace/api/member/dto/MemberProfileResponse.kt
  src/main/kotlin/com/beanspace/beanspace/api/member/dto/UpdateProfileRequest.kt
  src/main/kotlin/com/beanspace/beanspace/domain/image/model/ImageType.kt
  src/main/kotlin/com/beanspace/beanspace/domain/member/model/Member.kt
Labels: feature

#55 :bug: S3 Service 수정
  src/main/kotlin/com/beanspace/beanspace/infra/s3/S3Service.kt
Labels: bug

#61 :sparkles: ADMIN 권한 부여
  src/main/kotlin/com/beanspace/beanspace/api/admin/AdminController.kt
  src/main/kotlin/com/beanspace/beanspace/api/admin/AdminService.kt
  src/main/kotlin/com/beanspace/beanspace/api/member/dto/MemberListResponse.kt
Labels: feature

#63 ✨ CORS 문제 해결을 위한 Config 설정
  src/main/kotlin/com/beanspace/beanspace/api/member/dto/MemberProfileResponse.kt
  src/main/kotlin/com/beanspace/beanspace/infra/security/config/SecurityConfig.kt
Labels: feature

#65 ✅ SpaceQueryDslRepository.search() 테스트코드 추가
  build.gradle.kts
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepository.kt
  src/test/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepositoryTest.kt
Labels: test

#58 :sparkles: 카카오 소셜 로그인 기능 구현
  src/main/kotlin/com/beanspace/beanspace/api/auth/AuthService.kt
  src/main/kotlin/com/beanspace/beanspace/api/oauth/KakaoOAuth2Client.kt
  src/main/kotlin/com/beanspace/beanspace/api/oauth/OAuth2LoginController.kt
  src/main/kotlin/com/beanspace/beanspace/api/oauth/OAuth2LoginService.kt
  src/main/kotlin/com/beanspace/beanspace/api/oauth/dto/KakaoLoginUserInfoResponse.kt
  src/main/kotlin/com/beanspace/beanspace/api/oauth/dto/KakaoTokenResponse.kt
  src/main/kotlin/com/beanspace/beanspace/api/oauth/dto/KakaoUserPropertiesResponse.kt
  src/main/kotlin/com/beanspace/beanspace/domain/member/model/Member.kt
  src/main/kotlin/com/beanspace/beanspace/domain/member/repository/MemberRepository.kt
  src/main/kotlin/com/beanspace/beanspace/infra/restclient/RestClientConfig.kt
  src/main/kotlin/com/beanspace/beanspace/infra/security/config/SecurityConfig.kt
Labels: feature

#68 :bug: S3 이미지 버그 수정
  src/main/kotlin/com/beanspace/beanspace/api/image/ImageService.kt
  src/main/kotlin/com/beanspace/beanspace/api/image/dto/PreSignedUrlRequest.kt
  src/main/kotlin/com/beanspace/beanspace/domain/image/model/ImageType.kt
  src/main/kotlin/com/beanspace/beanspace/infra/s3/S3Service.kt
  src/main/kotlin/com/beanspace/beanspace/infra/security/config/SecurityConfig.kt
Labels: bug

#70 ✅ SpaceService 테스트코드 추가
  build.gradle.kts
  src/main/kotlin/com/beanspace/beanspace/api/space/SpaceController.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/SpaceService.kt
  src/main/kotlin/com/beanspace/beanspace/domain/reservation/repository/ReservationRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepositoryImpl.kt
  src/test/kotlin/com/beanspace/beanspace/api/space/SpaceServiceTest.kt
Labels: test

#73 🐛 쿠폰 발급 URI 오류 수정
  src/main/kotlin/com/beanspace/beanspace/api/coupon/CouponController.kt
  src/main/kotlin/com/beanspace/beanspace/domain/exception/GlobalExceptionHandler.kt
Labels: bug

#78 ✅ ReservationService 테스트코드 추가
  src/main/kotlin/com/beanspace/beanspace/api/reservation/ReservationController.kt
  src/main/kotlin/com/beanspace/beanspace/api/reservation/ReservationService.kt
  src/main/kotlin/com/beanspace/beanspace/domain/coupon/model/Coupon.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/model/Space.kt
  src/test/kotlin/com/beanspace/beanspace/api/reservation/ReservationServiceTest.kt
Labels: test

#80 ✨ 프론트에 필요한 response 정보 추가
  src/main/kotlin/com/beanspace/beanspace/api/space/SpaceController.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/SpaceService.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/HostResponse.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/ReviewResponse.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/SpaceDetailResponse.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/ReviewQueryDslRepository.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/ReviewQueryDslRepositoryImpl.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/ReviewRepository.kt
  src/test/kotlin/com/beanspace/beanspace/api/space/SpaceServiceTest.kt
  src/test/kotlin/com/beanspace/beanspace/domain/review/repository/ReviewRepositoryTest.kt
  src/test/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceQueryDslRepositoryTest.kt
Labels: feature, test

#82 :white_check_mark: AdminService 테스트 코드 추가
  src/test/kotlin/com/beanspace/beanspace/api/admin/AdminServiceTest.kt
Labels: test

#83 ✨ [Host] 등록한 공간목록 조회 기능 구현
  src/main/kotlin/com/beanspace/beanspace/api/host/HostController.kt
  src/main/kotlin/com/beanspace/beanspace/api/host/HostService.kt
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/SpaceResponse.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceRepository.kt
Labels: feature

#86 :sparkles: SpaceResponse에 우편번호 추가
  src/main/kotlin/com/beanspace/beanspace/api/space/dto/SpaceResponse.kt
Labels: feature

#90 🐛 [Host] 공간 목록 조회시 삭제된 공간 제외
  src/main/kotlin/com/beanspace/beanspace/api/host/HostService.kt
  src/main/kotlin/com/beanspace/beanspace/domain/space/repository/SpaceRepository.kt
Labels: bug
